// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import ()

type Scene struct {
	Workid      string      `json:"workid"`
	Act         int32       `json:"act"`
	Scene       int32       `json:"scene"`
	Description string      `json:"description"`
	Body        string      `json:"body"`
	FtsDocEn    interface{} `json:"fts_doc_en"`
}

type Work struct {
	Workid string `json:"workid"`
	Title  string `json:"title"`
}
