// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetScene(ctx context.Context, arg *GetSceneParams) (*GetSceneRow, error)
	GetWork(ctx context.Context, workid string) (string, error)
	Search(ctx context.Context, websearchToTsquery string) ([]*SearchRow, error)
}

var _ Querier = (*Queries)(nil)
